### PR TITLE
CSS style changed + minor changes

### PR DESCRIPTION
**Pull request by amivaleo**
Hi!

I changed the CSS of the note window and changed a few things in the labels following the HIGs.

I hope you will appreciate this.
:)

### CODE REVIEW

**Comment by Maestroschan** [comment]
Does it still behave in the same way when hovering ?

**Comment by amivaleo** [comment]
Yes. Of course the visual style is different but yes: "something" change when you hover the notes.
Try that! :)

**Comment by Maestroschan** [comment]
Oh. Flat design. Not very gnome-ish but it looks more modern i like it, maybe remove the border-radius from notestyle so it will look like actual sticky notes?

But my question was about extension.js, you removed a conditional handling the dynamic transparency, and your CSS doesn't handle it. Of course there is the shadow, which is a great idea, but i like my transparency (if CSS can't handle that, let my ugly hack with the conditional).

(Also, when a string is translatable i use double quote, and my CSS was with tabs.)

**Comment by amivaleo** [comment]
I consider those note windows as part of the shell which is... Well, I'd say it's flat. 🤔
That was just an idea anyway.
The CSS can handle the "is hovered" condition. That's why I removed your "hack" but I didn't restore the opacity changing behaviour because I thought the shadow made something similar. I can play with it a bit more. ;)
I'm sorry for the tabs: my gedit is set so that it uses spaces instead of tabs. I have to edit it.

I wasn't fully sure about the strings that have to be translated. The problem is: the extension is not localized in Italian although the Italian translation is there. 🤔 Does it work for you?
I was thinking about opening a few issue reports about this and other things.

I'll make a few changes later (~this evening), according to your reply here. 😊 I can't right now.
I hope you will like them more. ;)

**Comment by Maestroschan** [comment]
Yes translations works for me, maybe "it_IT" is too specific ? With "Emoji Selector" the folder is just "it" for example.

But using simple quote doesn't break translations at all, it's just a convention in GS code that i use in my code too

**Comment by amivaleo** [comment]
Uhm... Ok. I'll try to change the folder to just "it". 🤔

There must be another string which doesn't use the double quote. I can't look for it right now. I actually thought you preferred the single quote! :)
Nothing change for me anyway: I'll stick to your convention. 💪

Ps: why the "type here" string is vertically centered? O.o and what's the piece of code that makes it? I couldn't find it!

**Comment by Maestroschan** [comment]
It's the default behavior of this widget, i don't know how to override it

**Comment by Maestroschan** [comment]
concerning translations, i've add some scripts for generating correct and complete .po files

**Pull request closed without merging**
