### PR TITLE
Update italian translation

### PR DESCRIPTION
**Pull request by amivaleo**
Italian translation fixed.

Is there a way to avoid this ugly behaviour?
schermata da 2018-07-29 09-26-51
The italian translation for one of the strings takes a wider space, thus the window should be wider too. It can be resized manually, but it would be nice to have it already of the "right" width from the very beginning.
How do you do that? I am quite sure it's in the gschems.compiled file. How do you edit that?

### CODE REVIEW

**Comment by Maestroschan** [comment]
i didn't code the size, it's the default value

until i fix it, "(dis)attivare" ?

**Comment by amivaleo** [comment]
Ok, yes. That works.
Do I need to do another pull request for that? :(

**Comment by Maestroschan** [comment]
no it looks fine (but i'll read/try/merge later)

**Comment by Maestroschan** [comment]
oh, i'm stupid, it's just the translation i have nothing to test

**Pull request merged**
